# Generated by Django 4.1.1 on 2022-09-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='categories',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
