# Generated by Django 4.1.1 on 2022-09-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_alter_customers_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='department',
        ),
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('frozen food', 'frozen food'), ('fresh food', 'fresh food')], default='null', max_length=50, verbose_name='Product Type'),
        ),
    ]
