# Generated by Django 4.1.1 on 2022-09-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0003_remove_products_department_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('frozen food', 'frozen food'), ('fresh food', 'fresh food')], max_length=50, verbose_name='Product Type'),
        ),
    ]
