# Generated by Django 4.1.1 on 2022-09-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0004_alter_products_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(default=0, max_length=50, verbose_name='Password'),
        ),
    ]
